{{- if .Values.serviceAccountSL.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qs-sl.serviceAccountName" . }}
  labels:
    {{- include "qs-sl.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountSL.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}