apiVersion: v1
kind: Service
metadata:
  name: {{ include "qs-ui.fullname" . }}
  labels:
    {{- include "qs-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceUI.type }}
  ports:
    - port: {{ .Values.serviceUI.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qs-ui.selectorLabels" . | nindent 4 }}