{{- if .Values.serviceAccountUI.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qs-ui.serviceAccountName" . }}
  labels:
    {{- include "qs-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountUI.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}